exports.whitelist = require('./whitelist.js')
exports.setOcrConfig = require('./setOcrConfig.js')
exports.manageAllowlist = require('./manageAllowlist.js')
exports.setDonKey = require('./setDonKey')
exports.deployFullOracle = require('./deployFullOracle.js')